apiVersion: v1
kind: Pod
metadata:
  name: privilegie-interdit
  labels:
    app.kubernetes.io/name: privilegie-interdit
spec:
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.10
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 10m
          memory: 8Mi
        limits:
          cpu: 50m
          memory: 16Mi
