apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app.kubernetes.io/name: redis
data:
  REDIS_MAXMEMORY: 2mb
  redis.conf: |
    # Lab 05 — redis.conf monte via ConfigMap (pedagogique, pas un secret).
    bind 0.0.0.0
    port 6379
    protected-mode no
    daemonize no
    supervised no
    logfile ""
    dir /data
    save 3600 1
    appendonly no
    maxmemory 2mb
    maxmemory-policy allkeys-lru
