apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  securityContext:
    fsGroup: 999
  containers:
    - name: redis
      image: redis:7-alpine
      command:
        - redis-server
        - /usr/local/etc/redis/redis.conf
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: DB_PASSWORD
      ports:
        - name: redis
          containerPort: 6379
      readinessProbe:
        exec:
          command:
            - redis-cli
            - ping
        initialDelaySeconds: 3
        periodSeconds: 5
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 128Mi
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - name: config
          mountPath: /usr/local/etc/redis
          readOnly: true
        - name: data
          mountPath: /data
  volumes:
    - name: config
      configMap:
        name: redis-config
        defaultMode: 0644
        items:
          - key: redis.conf
            path: redis.conf
    - name: data
      emptyDir: {}
