apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: donnees
  labels:
    app.kubernetes.io/name: donnees
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
